### ISSUE TITLE
New management policy: ObserveUpdate

### ISSUE THREAD

**Issue by reegnz** [crossplane-contrib/provider-kubernetes#115]
There are some cases when you just want to patch a resource created by some other tool.

You deploy with `kubectl` directly, or your CD tool deploys the resource, and Crossplane composition patches it the first time it sees the resource, otherwise it should not create the resource, also it should not delete the resource.

### What problem are you facing?

In k8s it's common that it is not a single tool managing a resource, but multiple ones manage certain aspects of it.

### How could Crossplane help solve your problem?

The provider could work in a way where it only patches existing resources if they have been created, but otherwise just don't create the resource.

With the current management policies this is not possible really, An `ObserveUpdate` policy is missing.

**Comment by lsviben** [comment]
Hey, since [v0.11.0](https://github.com/crossplane-contrib/provider-kubernetes/releases/tag/v0.11.0) provider-kubernetes is using Crossplane native granular management policies. If you want to support ["Observe", "Update"] I suggest creating a ticket(or a PR if you have time) for [crossplane-runtime](https://github.com/crossplane/crossplane-runtime) to add this combination to the supported policies: https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reconciler/managed/policies.go#L46

**Comment by lsviben** [comment]
The ["Observe", "Update"] policy was added here: https://github.com/crossplane/crossplane-runtime/pull/692. 🎉

**Comment by lsviben** [comment]
Actually, we still need to consume the new xp-runtime version to be able to say this is done. Reopening
